(("site" . "kia's website") ("name" . "comment") ("version" . "2005-09-10") ("author" . "Noah S. Friedman") ("file" . "comment-20050910.lzh") ("src" . "http://www.geocities.jp/kiaswebsite/xyzzy/comment-20050910.lzh") ("description" . "comment out regions of buffers (Emacs版の移植です)") ("category") ("md5" . "8563d39effb32203a8408b251d07ef80") ("time" . 3335319706) ("depends") ("changes" . "行末の空白の扱いを変更しました") ("notice" . "ni-autoloadではキーバインドしませんので、適当なキーに割り当ててください。") ("load-after-install" . "") ("load-before-uninstall" . ""))
(("site" . "Junk Scripts") ("name" . "ruby-mode") ("version" . "0.0.2.2") ("author" . "Masashi Hattori <hat@kme.biglobe.ne.jp>") ("file" . "ruby-mode-0.0.2.2.lzh") ("src" . "http://www7a.biglobe.ne.jp/~hat/xyzzy/download.cgi?ruby-mode-0.0.2.2.lzh") ("description" . "Ruby書き用モード") ("category" "Development") ("md5" . "bb7feabbee1064e7efa10efcfa2c77bb") ("time" . 3341918636) ("depends") ("changes" . "ライセンスを適用とか。") ("notice" . "") ("load-after-install" . "") ("load-before-uninstall" . ""))
(("site" . "HIE no xyzzy") ("name" . "ruby-refe") ("version" . "2.00") ("author" . "HIE Masahiro") ("file" . "ruby-refe_2.00.zip") ("src" . "http://hie.s64.xrea.com/xyzzy/pub/ruby-refe_2.00.zip") ("description" . "ruby-mode から，ReFe を参照します。") ("category" "Documentation") ("md5" . "f2485dc589402273e45380e529e1df51") ("time" . 3479122615) ("depends") ("changes" . "[Version 2.00] 2010-04-01 (木)
・ReFe2 に対応した(はず)。
・ReFe1 非対応にした。
・オプションが指定できるようにした。
・その他いろいろ。") ("notice" . "ReFe2より前のバージョンには非対応。") ("load-after-install" . "") ("load-before-uninstall" . ""))
(("site" . "silog") ("name" . "paren") ("md5" . "a7d3ec008679baf596e93fca325eb500") ("src" . "http://white.s151.xrea.com/wiki/index.php?plugin=attach&refer=script%2Fparen&openfile=paren-2007.04.12.zip") ("version" . "2007.04.12") ("author" . "shiro") ("file" . "paren-2007.04.12.zip") ("description" . " KITAさん作のparen.lの改造版です
 
 以下変更点
  
  - ハイライトの前後で属性を保存
  - delete-text-attributesのタイミングの変更
  - エスケープされている場合は動作を行わないように
  - 指定されたコマンドの直後では動作を行わないように
  - シンタックスがタグの場合でもハイライト(設定可)
  - 閉じ括弧の反応する位置を1つ前にできるように(設定可)
  - ハイライト中でも元の属性を表示し続ける(設定可)") ("time" . 3385370028) ("depends" nil) ("category" "Utilities") ("changes" . "連続したエスケープの直後の括弧が強調できていなかったのを修正") ("notice" . "") ("load-after-install" . "") ("load-before-uninstall" . ""))
(("site" . "Junk Scripts") ("name" . "perl-misc") ("version" . "0.0.0.4") ("author" . "Masashi Hattori <hat@kme.biglobe.ne.jp>") ("file" . "perl-misc-0.0.0.4.lzh") ("src" . "http://www7a.biglobe.ne.jp/~hat/xyzzy/download.cgi?perl-misc-0.0.0.4.lzh") ("description" . "perl用マクロとか
- debug
- help
- list-function
- ...") ("category" "Development") ("md5" . "d6565acdc3990993ca3c8bff73d24037") ("time" . 3341918601) ("depends") ("changes" . "ライセンスを適用とか。") ("notice" . "") ("load-after-install" . "") ("load-before-uninstall" . ""))
(("site" . "xyzzy's Lisps") ("name" . "generic-comment-toggle") ("version" . "2008.01.07") ("author" . "bove-crach") ("file" . "generic-comment-toggle2008.01.07.zip") ("src" . "http://park.geocities.jp/bovecrach/xyzzy/generic-comment-toggle2008.01.07.zip") ("description" . "バッファモード毎のコメントアウトorアンコメントを行います。
要は HIEさんのページのNOTE->編集->1 行コメントをトグル を改造しただけです") ("category" "Development" "Editing") ("md5" . "8933fa328feb50e92cb422970000779f") ("time" . 3408629027) ("depends") ("changes" . "packagesとしては初版
・コメントアウト/アンコメントする度に行っていた(set-comment-words)を、最小限になるように。") ("notice" . "") ("load-after-install" . "") ("load-before-uninstall" . ""))
(("site" . "Junk Scripts") ("name" . "migemo") ("version" . "0.0.0.7") ("author" . "Masashi Hattori <hat@kme.biglobe.ne.jp>") ("file" . "migemo-0.0.0.7.lzh") ("src" . "http://www7a.biglobe.ne.jp/~hat/xyzzy/download.cgi?migemo-0.0.0.7.lzh") ("description" . "へなちょこMigemoインクリメンタルサーチマクロ") ("category" "Text Processing") ("md5" . "56d1ed351bf53348889cbb537784175c") ("time" . 3342092835) ("depends") ("changes" . "xyzzy Wikiの質問箱10(NANRIさん、ななし２さん)を取り込み。(__)") ("notice" . "migemo.dllが必要です。") ("load-after-install" . "") ("load-before-uninstall" . ""))
(("site" . "kia's website") ("name" . "template-insert") ("version" . "0.9") ("author" . "kia") ("file" . "template-insert-0.9.lzh") ("src" . "http://www.geocities.jp/kiaswebsite/xyzzy/template-insert-0.9.lzh") ("description" . "新しく作成するファイル名に応じたテンプレートをインサートします。") ("category") ("md5" . "545f8d19679d816063ba81978645be7e") ("time" . 3336621990) ("depends") ("changes" . "テンプレートが複数ある場合に選択できるようにしました。
`template-insert'パッケージにニックネーム`ti'を設定しました。
置換するキーワードを少し追加しました。") ("notice" . "") ("load-after-install" . "") ("load-before-uninstall" . ""))
