("name" . "ふかふか")
("author" . "fukae")
("url" . "http://www5e.biglobe.ne.jp/~fukafuka/")
("description" . "FukaFuka")
("packages" (("name" . "restore") ("version" . "2006.07.27") ("author" . "fukae") ("file" . "restore20060727.lzh") ("src" . "http://www5e.biglobe.ne.jp/~fukafuka/xyzzy/script/restore/restore20060727.lzh") ("description" . "ポイント、色づけ、グローバルマークを保存するバッファを \"表示(V)\" メニューから
指定できるようにします。") ("category" "Utilities") ("md5" . "3978117954e9c41e161a65b222cae71c") ("time" . 3362965810) ("depends") ("changes" . "公開。") ("notice" . "") ("load-after-install" . "") ("load-before-uninstall" . "")) (("name" . "psearch") ("version" . "2006.07.27") ("author" . "fukae") ("file" . "psearch20060727.lzh") ("src" . "http://www5e.biglobe.ne.jp/~fukafuka/xyzzy/script/psearch/psearch20060727.lzh") ("description" . "popup-listを使って検索を行います") ("category" "Text Processing") ("md5" . "1a8e61326e465c2fb5c0824ad82ce1b8") ("time" . 3362964344) ("depends") ("changes" . "isearch 用の設定を変更。
その他、細かい修正。") ("notice" . "") ("load-after-install" . "") ("load-before-uninstall" . "")) (("name" . "open-backup") ("version" . "2006.07.27") ("author" . "fukae") ("file" . "open-backup20060727.lzh") ("src" . "http://www5e.biglobe.ne.jp/~fukafuka/xyzzy/script/open-backup/open-backup20060727.lzh") ("description" . "バックアップファイルを開きます") ("category" "Utilities") ("md5" . "699549276c48c50c60257bad2dc15903") ("time" . 3362964252) ("depends") ("changes" . "全削除のメッセージを変更。") ("notice" . "") ("load-after-install" . "") ("load-before-uninstall" . "")) (("name" . "ee") ("version" . "2006.07.27") ("author" . "fukae") ("file" . "ee20060727.lzh") ("src" . "http://www5e.biglobe.ne.jp/~fukafuka/xyzzy/tips/ee/ee20060727.lzh") ("description" . "英々辞書を使うための lisp です") ("category" "Utilities") ("md5" . "cc10daa4dccf2825fb5e1e97636e31c4") ("time" . 3362964136) ("depends") ("changes" . "ロングマン英々辞典(第3版)対応をやめた。
conjugation に対応。") ("notice" . "") ("load-after-install" . "") ("load-before-uninstall" . "")) (("name" . "autolookup") ("version" . "2006.07.27") ("author" . "fukae") ("file" . "autolookup20060727.lzh") ("src" . "http://www5e.biglobe.ne.jp/~fukafuka/xyzzy/script/autolookup/autolookup20060727.lzh") ("description" . "カーソル下の英単語の訳をステータスバーに表示します") ("category" "Utilities") ("md5" . "c9e8ff69493d274577e5a38cd500e34a") ("time" . 3362964008) ("depends") ("changes" . "細かい修正。") ("notice" . "") ("load-after-install" . "") ("load-before-uninstall" . "")) (("name" . "changelogmemo") ("version" . "2006.03.08") ("author" . "fukae") ("file" . "changelogmemo20060308.lzh") ("src" . "http://www5e.biglobe.ne.jp/~fukafuka/xyzzy/script/changelogmemo/changelogmemo20060308.lzh") ("description" . "changelog でメモをとります") ("category" "Utilities") ("md5" . "29053e3a65459db4466579db26dc96f3") ("time" . 3350751656) ("depends") ("changes" . "行頭にタブがない chalow 用の書式(* タイトル [カテゴリ]・・[カテゴリ]: 本文)
にした。
C-x C-s でメモを保存するように変えた。
*scratch* バッファをメモバッファとして使うようにした。
検索の種類をふやした。(google, 正規表現, or, カテゴリ, 日付, migemo)
絞込み検索のやり方を変更。
検索画面から直接編集できるようにした。
カテゴリを設定しておかなくても補完できるようにした。
ツールバーでメモをとれるようにした。
複数の CLファイルに対応。
ライセンスを適用。
その他、いろいろ変えた。") ("notice" . "書式を変更したので、CL ファイルを変換しないと使えなくなりました。
お手数ですが、readme.txt を御覧ください。") ("load-after-install" . "") ("load-before-uninstall" . "")) (("name" . "mathematica") ("version" . "2006.03.08") ("author" . "fukae") ("file" . "mathematica20060308.lzh") ("src" . "http://www5e.biglobe.ne.jp/~fukafuka/xyzzy/script/mathematica/mathematica20060308.lzh") ("description" . "mathematica.el の移植です") ("category" "Editing") ("md5" . "3d6bd282e143062e07ff413d358326af") ("time" . 3350735846) ("depends") ("changes" . "細かい修正。") ("notice" . "") ("load-after-install" . "") ("load-before-uninstall" . "")))
